name: Build NamkhingCake

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: RealOrCake

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install pyinstaller

      - run: |
          pyinstaller --onefile --windowed \
            --add-data "assets;assets" \
            --add-data "states;states" \
            --add-data "decoModule;decoModule" \
            main.py

      - uses: actions/upload-artifact@v3
        with:
          name: NamkhingCake-Windows
          path: dist/main.exe

  build-macos:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: RealOrCake

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install pyinstaller

      - run: |
          pyinstaller --onefile \
            --add-data "assets:assets" \
            --add-data "states:states" \
            --add-data "decoModule:decoModule" \
            main.py

      - uses: actions/upload-artifact@v3
        with:
          name: NamkhingCake-macOS
          path: dist/main
